
package clientImported;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "USPSTrackingServiceSOAPService", targetNamespace = "http://endpoint.service.usps.services/", wsdlLocation = "http://localhost:9876/uspsTracking?wsdl")
public class USPSTrackingServiceSOAPService
    extends Service
{

    private final static URL USPSTRACKINGSERVICESOAPSERVICE_WSDL_LOCATION;
    private final static WebServiceException USPSTRACKINGSERVICESOAPSERVICE_EXCEPTION;
    private final static QName USPSTRACKINGSERVICESOAPSERVICE_QNAME = new QName("http://endpoint.service.usps.services/", "USPSTrackingServiceSOAPService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9876/uspsTracking?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USPSTRACKINGSERVICESOAPSERVICE_WSDL_LOCATION = url;
        USPSTRACKINGSERVICESOAPSERVICE_EXCEPTION = e;
    }

    public USPSTrackingServiceSOAPService() {
        super(__getWsdlLocation(), USPSTRACKINGSERVICESOAPSERVICE_QNAME);
    }

    public USPSTrackingServiceSOAPService(WebServiceFeature... features) {
        super(__getWsdlLocation(), USPSTRACKINGSERVICESOAPSERVICE_QNAME, features);
    }

    public USPSTrackingServiceSOAPService(URL wsdlLocation) {
        super(wsdlLocation, USPSTRACKINGSERVICESOAPSERVICE_QNAME);
    }

    public USPSTrackingServiceSOAPService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USPSTRACKINGSERVICESOAPSERVICE_QNAME, features);
    }

    public USPSTrackingServiceSOAPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public USPSTrackingServiceSOAPService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns USPSTrackingServiceSOAP
     */
    @WebEndpoint(name = "USPSTrackingServiceSOAPPort")
    public USPSTrackingServiceSOAP getUSPSTrackingServiceSOAPPort() {
        return super.getPort(new QName("http://endpoint.service.usps.services/", "USPSTrackingServiceSOAPPort"), USPSTrackingServiceSOAP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns USPSTrackingServiceSOAP
     */
    @WebEndpoint(name = "USPSTrackingServiceSOAPPort")
    public USPSTrackingServiceSOAP getUSPSTrackingServiceSOAPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://endpoint.service.usps.services/", "USPSTrackingServiceSOAPPort"), USPSTrackingServiceSOAP.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USPSTRACKINGSERVICESOAPSERVICE_EXCEPTION!= null) {
            throw USPSTRACKINGSERVICESOAPSERVICE_EXCEPTION;
        }
        return USPSTRACKINGSERVICESOAPSERVICE_WSDL_LOCATION;
    }

}
